### ISSUE TITLE
Model for Addons Timeline Panel

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-editor#49]
## Description
From the wireframe, we should have a model in PenPot fully describing the functionality of the panel and its components.

## Requirements
- [x] Model existing in PenPot

**Model should have**
- [x] Timeline
- [x] Timeline Scroll Bar
- [x] Current System state overview
  - List all system entities in the current state
  - highlights with green added Entities
  - highlights with red deleted Entities
  - highlights with yellow modified Entities
  - Represent addition/Removal/Modification of attributes and properties of Entities as well
- [x] Editing Addon fields
  - Name
  - Which Addon it is
  - Where to load it from (Select from NPM, URL, File)
  - Addon Configuration (Object Definition Signature)

**Comment by lukineas** [comment]
The design:

![Image](https://github.com/user-attachments/assets/9497e0c1-fea5-46f5-a244-bed580aac301)


Some of the functionality:
> simplified timeline on the left
- identifies the selected addon from the listed order
- allows navigating to the selected icon from addon timeline order

> addon timeline in the center
- also identifies the selected addon from the list
- new addons can be added from the top and bottom of the list (button)
- displays the loading order for the addons
- each card can have its name changed
- the cog icon is clicked to edit the addon's config
- addons can be reordered by 'drag and drop'
- addons can be deleted
- the user might change where the addon is loaded from
- the user might change the addon's location

> system state on the selected addon
- displays the current system state at the selected addon
- lists the changes in categories (Addons, Schemas and BOps)
- cards display informative tooltips on click, showcasing a more detailed analysis

**Comment by lukineas** [comment]
Reminder for myself to add the editing button on Addon cards
